version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1
  snyk: snyk/snyk@1.7.0

jobs:
  scan:
    docker:
      - image: cimg/go:1.21.0-node
    steps:
      - checkout
      - snyk/install
  security-scans:
    resource_class: small
    docker:
      - image: cimg/go:1.22
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: cli-alerts
      - security-scans:
          context: devex_cli
      - scan:
          context: hammerhead-snyk-orb-snyk-creds
