/*
 * © 2026 Snyk Limited
 *
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package classifications_test

import (
	"testing"

	"github.com/snyk/error-catalog-golang-public/classifications"
)

// TestClassify_KnownCodes spot-checks Classify against every known error
// code, so a regression in the lookup itself (not just a stale map) fails
// loudly with the offending code named.
func TestClassify_KnownCodes(t *testing.T) {
	tests := []struct {
		code string
		want classifications.Classification
	}{
		{want: classifications.Unsupported, code: "PR-FAILURES-0001"},
		{want: classifications.Actionable, code: "PR-FAILURES-0002"},
		{want: classifications.Actionable, code: "PR-FAILURES-0003"},
		{want: classifications.Actionable, code: "SNYK-0001"},
		{want: classifications.Unsupported, code: "SNYK-0002"},
		{want: classifications.Actionable, code: "SNYK-0003"},
		{want: classifications.Unexpected, code: "SNYK-0004"},
		{want: classifications.Actionable, code: "SNYK-0005"},
		{want: classifications.Actionable, code: "SNYK-0006"},
		{want: classifications.Actionable, code: "SNYK-0007"},
		{want: classifications.Unexpected, code: "SNYK-0008"},
		{want: classifications.Unexpected, code: "SNYK-0009"},
		{want: classifications.Actionable, code: "SNYK-0010"},
		{want: classifications.Unsupported, code: "SNYK-0099"},
		{want: classifications.Unexpected, code: "SNYK-9999"},
		{want: classifications.Unexpected, code: "SNYK-AIBOM-0001"},
		{want: classifications.Actionable, code: "SNYK-AIBOM-0002"},
		{want: classifications.Actionable, code: "SNYK-AIBOM-0003"},
		{want: classifications.Actionable, code: "SNYK-CBI-0001"},
		{want: classifications.Actionable, code: "SNYK-CBI-0002"},
		{want: classifications.Actionable, code: "SNYK-CBI-0003"},
		{want: classifications.Unsupported, code: "SNYK-CBI-0004"},
		{want: classifications.Actionable, code: "SNYK-CBI-0005"},
		{want: classifications.Actionable, code: "SNYK-CBI-0006"},
		{want: classifications.Actionable, code: "SNYK-CBI-0007"},
		{want: classifications.Actionable, code: "SNYK-CBI-0008"},
		{want: classifications.Actionable, code: "SNYK-CBI-0009"},
		{want: classifications.Actionable, code: "SNYK-CBI-0010"},
		{want: classifications.Actionable, code: "SNYK-CBI-0011"},
		{want: classifications.Actionable, code: "SNYK-CBI-0012"},
		{want: classifications.Actionable, code: "SNYK-CBI-0013"},
		{want: classifications.Unexpected, code: "SNYK-CBI-0014"},
		{want: classifications.Unexpected, code: "SNYK-CBI-0015"},
		{want: classifications.Unexpected, code: "SNYK-CBI-0016"},
		{want: classifications.Unexpected, code: "SNYK-CBI-0017"},
		{want: classifications.Unexpected, code: "SNYK-CBI-0018"},
		{want: classifications.Actionable, code: "SNYK-CBI-0019"},
		{want: classifications.Unexpected, code: "SNYK-CLI-0000"},
		{want: classifications.Actionable, code: "SNYK-CLI-0001"},
		{want: classifications.Actionable, code: "SNYK-CLI-0002"},
		{want: classifications.Actionable, code: "SNYK-CLI-0003"},
		{want: classifications.Actionable, code: "SNYK-CLI-0004"},
		{want: classifications.Unexpected, code: "SNYK-CLI-0005"},
		{want: classifications.Actionable, code: "SNYK-CLI-0006"},
		{want: classifications.Actionable, code: "SNYK-CLI-0007"},
		{want: classifications.Actionable, code: "SNYK-CLI-0008"},
		{want: classifications.Actionable, code: "SNYK-CLI-0009"},
		{want: classifications.Actionable, code: "SNYK-CLI-0010"},
		{want: classifications.Unexpected, code: "SNYK-CLI-0011"},
		{want: classifications.Unexpected, code: "SNYK-CLI-0012"},
		{want: classifications.Unexpected, code: "SNYK-CLI-0013"},
		{want: classifications.Unsupported, code: "SNYK-CLI-0014"},
		{want: classifications.Actionable, code: "SNYK-CLI-0015"},
		{want: classifications.Actionable, code: "SNYK-CLI-0016"},
		{want: classifications.Actionable, code: "SNYK-CLI-0017"},
		{want: classifications.Actionable, code: "SNYK-CLI-0018"},
		{want: classifications.Actionable, code: "SNYK-CLI-0019"},
		{want: classifications.Actionable, code: "SNYK-CLI-0020"},
		{want: classifications.Actionable, code: "SNYK-CLI-0021"},
		{want: classifications.Actionable, code: "SNYK-CLI-0022"},
		{want: classifications.Unexpected, code: "SNYK-CLI-0023"},
		{want: classifications.Unexpected, code: "SNYK-CLI-0024"},
		{want: classifications.Actionable, code: "SNYK-CLI-0025"},
		{want: classifications.Actionable, code: "SNYK-CLI-0026"},
		{want: classifications.Actionable, code: "SNYK-CLI-0027"},
		{want: classifications.Actionable, code: "SNYK-CLI-0028"},
		{want: classifications.Unsupported, code: "SNYK-CODE-0001"},
		{want: classifications.Unsupported, code: "SNYK-CODE-0002"},
		{want: classifications.Unsupported, code: "SNYK-CODE-0003"},
		{want: classifications.Actionable, code: "SNYK-CODE-0004"},
		{want: classifications.Actionable, code: "SNYK-CODE-0005"},
		{want: classifications.Actionable, code: "SNYK-CODE-0006"},
		{want: classifications.Actionable, code: "SNYK-CODE-0007"},
		{want: classifications.Actionable, code: "SNYK-CODE-0009"},
		{want: classifications.Actionable, code: "SNYK-CODE-0010"},
		{want: classifications.Actionable, code: "SNYK-CODE-0011"},
		{want: classifications.Actionable, code: "SNYK-CODE-0012"},
		{want: classifications.Actionable, code: "SNYK-CODE-0013"},
		{want: classifications.Actionable, code: "SNYK-CODE-0014"},
		{want: classifications.Actionable, code: "SNYK-INTEGRATION-0001"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0001"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0002"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0003"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0004"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0005"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0006"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0007"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0008"},
		{want: classifications.Actionable, code: "SNYK-OPENAPI-0009"},
		{want: classifications.Actionable, code: "SNYK-OS-0001"},
		{want: classifications.Actionable, code: "SNYK-OS-0002"},
		{want: classifications.Actionable, code: "SNYK-OS-0003"},
		{want: classifications.Actionable, code: "SNYK-OS-0004"},
		{want: classifications.Actionable, code: "SNYK-OS-0005"},
		{want: classifications.Actionable, code: "SNYK-OS-0006"},
		{want: classifications.Unexpected, code: "SNYK-OS-0007"},
		{want: classifications.Unexpected, code: "SNYK-OS-0008"},
		{want: classifications.Unsupported, code: "SNYK-OS-0009"},
		{want: classifications.Actionable, code: "SNYK-OS-0010"},
		{want: classifications.Unsupported, code: "SNYK-OS-0011"},
		{want: classifications.Actionable, code: "SNYK-OS-0012"},
		{want: classifications.Actionable, code: "SNYK-OS-0013"},
		{want: classifications.Unexpected, code: "SNYK-OS-7001"},
		{want: classifications.Actionable, code: "SNYK-OS-8001"},
		{want: classifications.Actionable, code: "SNYK-OS-8002"},
		{want: classifications.Actionable, code: "SNYK-OS-8003"},
		{want: classifications.Actionable, code: "SNYK-OS-8004"},
		{want: classifications.Actionable, code: "SNYK-OS-8005"},
		{want: classifications.Unexpected, code: "SNYK-OS-8006"},
		{want: classifications.Unexpected, code: "SNYK-OS-9000"},
		{want: classifications.Unexpected, code: "SNYK-OS-9001"},
		{want: classifications.Unexpected, code: "SNYK-OS-9002"},
		{want: classifications.Unsupported, code: "SNYK-OS-9003"},
		{want: classifications.Unsupported, code: "SNYK-OS-9004"},
		{want: classifications.Actionable, code: "SNYK-OS-9005"},
		{want: classifications.Actionable, code: "SNYK-OS-9006"},
		{want: classifications.Actionable, code: "SNYK-OS-9007"},
		{want: classifications.Actionable, code: "SNYK-OS-9008"},
		{want: classifications.Unsupported, code: "SNYK-OS-DOTNET-0001"},
		{want: classifications.Unsupported, code: "SNYK-OS-DOTNET-0002"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0003"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0004"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0005"},
		{want: classifications.Unsupported, code: "SNYK-OS-DOTNET-0006"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0007"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0008"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0009"},
		{want: classifications.Unsupported, code: "SNYK-OS-DOTNET-0010"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0011"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0012"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0013"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0014"},
		{want: classifications.Actionable, code: "SNYK-OS-DOTNET-0015"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0001"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0002"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0003"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0004"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0005"},
		{want: classifications.Unsupported, code: "SNYK-OS-GO-0006"},
		{want: classifications.Unsupported, code: "SNYK-OS-GO-0007"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0008"},
		{want: classifications.Unexpected, code: "SNYK-OS-GO-0009"},
		{want: classifications.Unsupported, code: "SNYK-OS-GO-0010"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0011"},
		{want: classifications.Unexpected, code: "SNYK-OS-GO-0012"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0013"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0014"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0015"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0016"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0017"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0018"},
		{want: classifications.Actionable, code: "SNYK-OS-GO-0019"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0001"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0002"},
		{want: classifications.Unexpected, code: "SNYK-OS-MAVEN-0003"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0004"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0005"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0006"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0007"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0008"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0009"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0010"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0011"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0012"},
		{want: classifications.Unexpected, code: "SNYK-OS-MAVEN-0013"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0014"},
		{want: classifications.Unsupported, code: "SNYK-OS-MAVEN-0015"},
		{want: classifications.Unexpected, code: "SNYK-OS-MAVEN-0016"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0017"},
		{want: classifications.Actionable, code: "SNYK-OS-MAVEN-0018"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0001"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0002"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0003"},
		{want: classifications.Unexpected, code: "SNYK-OS-NODEJS-0004"},
		{want: classifications.Unsupported, code: "SNYK-OS-NODEJS-0005"},
		{want: classifications.Unexpected, code: "SNYK-OS-NODEJS-0006"},
		{want: classifications.Unexpected, code: "SNYK-OS-NODEJS-0007"},
		{want: classifications.Unexpected, code: "SNYK-OS-NODEJS-0008"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0009"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0010"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0011"},
		{want: classifications.Unexpected, code: "SNYK-OS-NODEJS-0012"},
		{want: classifications.Unexpected, code: "SNYK-OS-NODEJS-0013"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0014"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0015"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0016"},
		{want: classifications.Unsupported, code: "SNYK-OS-NODEJS-0017"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0019"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0020"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0021"},
		{want: classifications.Actionable, code: "SNYK-OS-NODEJS-0022"},
		{want: classifications.Unsupported, code: "SNYK-OS-PYTHON-0001"},
		{want: classifications.Unsupported, code: "SNYK-OS-PYTHON-0002"},
		{want: classifications.Unexpected, code: "SNYK-OS-PYTHON-0003"},
		{want: classifications.Actionable, code: "SNYK-OS-PYTHON-0004"},
		{want: classifications.Actionable, code: "SNYK-OS-PYTHON-0005"},
		{want: classifications.Actionable, code: "SNYK-OS-PYTHON-0006"},
		{want: classifications.Actionable, code: "SNYK-OS-PYTHON-0007"},
		{want: classifications.Actionable, code: "SNYK-OS-PYTHON-0008"},
		{want: classifications.Unsupported, code: "SNYK-OS-PYTHON-0009"},
		{want: classifications.Actionable, code: "SNYK-OS-PYTHON-0010"},
		{want: classifications.Actionable, code: "SNYK-OS-PYTHON-0011"},
		{want: classifications.Unsupported, code: "SNYK-OS-PYTHON-0012"},
		{want: classifications.Actionable, code: "SNYK-OS-PYTHON-0013"},
		{want: classifications.Unexpected, code: "SNYK-OS-PYTHON-0014"},
		{want: classifications.Actionable, code: "SNYK-OS-RUBY-0001"},
		{want: classifications.Actionable, code: "SNYK-OS-RUBY-0002"},
		{want: classifications.Actionable, code: "SNYK-OS-RUBY-0003"},
		{want: classifications.Actionable, code: "SNYK-OS-SETTINGS-0001"},
		{want: classifications.Actionable, code: "SNYK-OS-UV-0001"},
		{want: classifications.Unexpected, code: "SNYK-OSJVM-001"},
		{want: classifications.Actionable, code: "SNYK-OSJVM-002"},
		{want: classifications.Actionable, code: "SNYK-OSSI-1040"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-1050"},
		{want: classifications.Actionable, code: "SNYK-OSSI-2010"},
		{want: classifications.Actionable, code: "SNYK-OSSI-2011"},
		{want: classifications.Actionable, code: "SNYK-OSSI-2020"},
		{want: classifications.Actionable, code: "SNYK-OSSI-2021"},
		{want: classifications.Actionable, code: "SNYK-OSSI-2022"},
		{want: classifications.Actionable, code: "SNYK-OSSI-2030"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-2031"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-2032"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-2033"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-2040"},
		{want: classifications.Actionable, code: "SNYK-OSSI-2041"},
		{want: classifications.Unsupported, code: "SNYK-OSSI-2042"},
		{want: classifications.Unsupported, code: "SNYK-OSSI-2043"},
		{want: classifications.Unsupported, code: "SNYK-OSSI-2044"},
		{want: classifications.Unsupported, code: "SNYK-OSSI-2045"},
		{want: classifications.Actionable, code: "SNYK-OSSI-2046"},
		{want: classifications.Unsupported, code: "SNYK-OSSI-2047"},
		{want: classifications.Unsupported, code: "SNYK-OSSI-2048"},
		{want: classifications.Actionable, code: "SNYK-OSSI-OSPI-1001"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-OSPI-1002"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-OSPI-2001"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-OSPI-3001"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-OSPI-4001"},
		{want: classifications.Actionable, code: "SNYK-OSSI-OSPSS-1001"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-OSPSS-1002"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-OSPSS-2001"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-OSPSS-3001"},
		{want: classifications.Unexpected, code: "SNYK-OSSI-OSPSS-4001"},
		{want: classifications.Unsupported, code: "SNYK-PACKAGES-0001"},
		{want: classifications.Actionable, code: "SNYK-PACKAGES-0003"},
		{want: classifications.Actionable, code: "SNYK-PACKAGES-0005"},
		{want: classifications.Actionable, code: "SNYK-PACKAGES-0006"},
		{want: classifications.Actionable, code: "SNYK-PACKAGES-0007"},
		{want: classifications.Actionable, code: "SNYK-PACKAGES-0008"},
		{want: classifications.Actionable, code: "SNYK-PACKAGES-0009"},
		{want: classifications.Actionable, code: "SNYK-POLICY-0001"},
		{want: classifications.Actionable, code: "SNYK-POLICY-0002"},
		{want: classifications.Actionable, code: "SNYK-PR-CHECK-0001"},
		{want: classifications.Actionable, code: "SNYK-PR-CHECK-0002"},
		{want: classifications.Actionable, code: "SNYK-PR-CHECK-0003"},
		{want: classifications.Actionable, code: "SNYK-PR-CHECK-0004"},
		{want: classifications.Unexpected, code: "SNYK-PR-CHECK-0005"},
		{want: classifications.Unexpected, code: "SNYK-PR-CHECK-0006"},
		{want: classifications.Unexpected, code: "SNYK-PR-CHECK-0007"},
		{want: classifications.Actionable, code: "SNYK-PR-CHECK-0008"},
		{want: classifications.Unexpected, code: "SNYK-PR-CHECK-0009"},
		{want: classifications.Actionable, code: "SNYK-PR-CHECK-0010"},
		{want: classifications.Unexpected, code: "SNYK-PR-CHECK-0011"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0001"},
		{want: classifications.Actionable, code: "SNYK-PR-TEMPLATE-0002"},
		{want: classifications.Actionable, code: "SNYK-PR-TEMPLATE-0003"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0004"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0005"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0006"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0007"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0008"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0009"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0010"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0011"},
		{want: classifications.Unexpected, code: "SNYK-PR-TEMPLATE-0012"},
		{want: classifications.Unexpected, code: "SNYK-RIFT-0001"},
		{want: classifications.Unexpected, code: "SNYK-SBOM-0001"},
		{want: classifications.Actionable, code: "SNYK-SBOM-0002"},
		{want: classifications.Unexpected, code: "SNYK-SBOM-0003"},
		{want: classifications.Unsupported, code: "SNYK-SBOM-0004"},
		{want: classifications.Unsupported, code: "SNYK-SBOM-0005"},
		{want: classifications.Unsupported, code: "SNYK-SBOM-0006"},
		{want: classifications.Unsupported, code: "SNYK-SBOM-0007"},
		{want: classifications.Unsupported, code: "SNYK-SBOM-0008"},
		{want: classifications.Unsupported, code: "SNYK-SBOM-0009"},
		{want: classifications.Unsupported, code: "SNYK-SBOM-0010"},
		{want: classifications.Unsupported, code: "SNYK-SCM-0001"},
		{want: classifications.Actionable, code: "SNYK-SCM-0002"},
		{want: classifications.Actionable, code: "SNYK-SCM-0003"},
		{want: classifications.Actionable, code: "SNYK-SCM-0004"},
		{want: classifications.Unsupported, code: "SNYK-SCM-0005"},
		{want: classifications.Unsupported, code: "SNYK-SCM-0006"},
		{want: classifications.Actionable, code: "SNYK-SCM-0010"},
		{want: classifications.Unexpected, code: "SNYK-SECRETS-0001"},
		{want: classifications.Actionable, code: "SNYK-SECRETS-0002"},
		{want: classifications.Unexpected, code: "SNYK-SECRETS-0003"},
		{want: classifications.Actionable, code: "SNYK-TARGET-0001"},
		{want: classifications.Actionable, code: "SNYK-TARGET-0002"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0001"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0002"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0003"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0004"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0005"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0006"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0007"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0008"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0009"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0010"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0011"},
		{want: classifications.Actionable, code: "SNYK-UPLOAD-REVISION-0012"},
	}

	if len(tests) == 0 {
		t.Fatal("no error codes generated into the classifications map — this test asserts nothing without them")
	}

	for _, tt := range tests {
		t.Run(tt.code, func(t *testing.T) {
			if got := classifications.Classify(tt.code); got != tt.want {
				t.Errorf("Classify(%q) = %v, want %v", tt.code, got, tt.want)
			}
		})
	}
}

func TestClassify_UnknownCode(t *testing.T) {
	if got := classifications.Classify("SNYK-DOES-NOT-EXIST"); got != classifications.Unknown {
		t.Errorf("Classify(unknown code) = %v, want %v", got, classifications.Unknown)
	}
}

func TestClassify_EmptyString(t *testing.T) {
	if got := classifications.Classify(""); got != classifications.Unknown {
		t.Errorf(`Classify("") = %v, want %v`, got, classifications.Unknown)
	}
}

// TestClassifications_EveryCodeHasKnownClassification is the freshness
// guarantee for the generator. It fails if any code in the catalog was
// generated without a classification.
func TestClassifications_EveryCodeHasKnownClassification(t *testing.T) {
	for code, got := range classifications.Classifications {
		switch got {
		case classifications.Unexpected, classifications.Actionable, classifications.Unsupported:
			// Known classification.
		default:
			t.Errorf("code %s has unexpected classification %v", code, got)
		}
	}
}
